on:
  push:
    branches:
      - master

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-Latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: Cache Flutter build outputs
        uses: actions/cache@v3
        with:
          path: build/app/outputs/apk/release
          key: ${{ runner.os }}-apk-${{ hashFiles('pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-apk-

      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.0
          token: ${{ secrets.TOKEN}}